### PR TITLE
Removed trailing newline in branch normal output

### PR DESCRIPTION
**Pull request by Nonoelgringo**
Remove the trailing newline in returned output from `_handle_normal_output`
This helps for counting branches accurately with wc.
We cannot use rstrip because the styling that can be applied after the newline.

### CODE REVIEW

**Review by XN137 — COMMENTED** [review]
couldnt we remove the `\n` from line 134
and collect rows into a list

and finally `return "\n".join(output_rows)` ?

**Comment by Nonoelgringo** [comment]
hey, sure ! I went with the solution that didn't change the loop code but if you prefer this way I don't mind tbh
let me know and I'll update the PR

**Comment by XN137** [comment]
imo we should prefer to touch the loop code instead of adding new code to fix its result up afterwards

**Comment by XN137** [comment]
looks good thanks for the update, @Nonoelgringo did you sign the CLA yet? (see comments in PR)

**Comment by Nonoelgringo** [comment]
np :) I did not sign the CLA yet, I'll check that today (I assume my compamy will want to see it too) and let you know, thank you

**Comment by Nonoelgringo** [comment]
@XN137, I signed the CLA

**Comment by XN137** [comment]
@Nonoelgringo thanks! we've recently changed the test infrastructure, could you rebase or merge latest master? then we can have a final CI run

**Review by XN137 — APPROVED** [review]

**Comment by XN137** [comment]
@Nonoelgringo thanks for the contribution and sorry for the initial overhead

**Pull request merged**
